version: "3.3"

services:

  mosquitto:
    image: mosquitto
    hostname: mosquitto
    container_name: mosquitto
    privileged: true
    env_file:
      - ./environment
    ports:
      - "1883:1883"

  forwarder:
    image: forwarder
    hostname: forwarder
    container_name: forwarder
    privileged: true
    env_file:
      - ./environment
    links:
      - mosquitto

  facedetector:
    image: facedetector
    hostname: facedetector
    container_name: facedetector
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
    env_file:
      - ./environment
    links:
      - forwarder
    volumes:
      - /tmp:/tmp

networks:
  default:
